// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0in5p0wpEgzR3ZtWZAtnK3kqyX9WXXTY',
    appId: '1:53580920739:web:d6478e196123df9265cc16',
    messagingSenderId: '53580920739',
    projectId: 'cashflow-e54a0',
    authDomain: 'cashflow-e54a0.firebaseapp.com',
    storageBucket: 'cashflow-e54a0.appspot.com',
    measurementId: 'G-2DEN2C750P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxJlYcag0TxzUfEPVDdHI0MSbvsLFh9ys',
    appId: '1:53580920739:android:85e521c7520f1b3365cc16',
    messagingSenderId: '53580920739',
    projectId: 'cashflow-e54a0',
    storageBucket: 'cashflow-e54a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDe3ZOCyTXDMg4QNW6do5VVAddUomVt6I',
    appId: '1:53580920739:ios:260966c0528969bf65cc16',
    messagingSenderId: '53580920739',
    projectId: 'cashflow-e54a0',
    storageBucket: 'cashflow-e54a0.appspot.com',
    iosBundleId: 'com.example.myCashflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDe3ZOCyTXDMg4QNW6do5VVAddUomVt6I',
    appId: '1:53580920739:ios:260966c0528969bf65cc16',
    messagingSenderId: '53580920739',
    projectId: 'cashflow-e54a0',
    storageBucket: 'cashflow-e54a0.appspot.com',
    iosBundleId: 'com.example.myCashflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0in5p0wpEgzR3ZtWZAtnK3kqyX9WXXTY',
    appId: '1:53580920739:web:c8b4a6d61c15de6165cc16',
    messagingSenderId: '53580920739',
    projectId: 'cashflow-e54a0',
    authDomain: 'cashflow-e54a0.firebaseapp.com',
    storageBucket: 'cashflow-e54a0.appspot.com',
    measurementId: 'G-1T3Q5KGHRW',
  );
}
